#pragma once
#include <cstdio>
#include <init.h>
#include <ros.h>
#include <std_msgs/String.h>
#include <stm32f4xx_hal.h>

#ifdef NUCLEO

#define BOARD 1

#define SWD_PORT_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define ROSSERIAL_UART USART3
#define ROSSERIAL_UART_IRQn USART3_IRQn
#define ROSSERIAL_UART_CLK_EN __HAL_RCC_USART3_CLK_ENABLE
#define ROSSERIAL_UART_RXDMA_STREAM DMA1_Stream1
#define ROSSERIAL_UART_TXDMA_STREAM DMA2_Stream3
#define ROSSERIAL_UART_RXDMA_CHANNEL DMA_CHANNEL_4
#define ROSSERIAL_UART_TXDMA_CHANNEL DMA_CHANNEL_4
#define ROSSERIAL_UART_RXDMA_IRQn DMA1_Stream1_IRQn
#define ROSSERIAL_UART_TXDMA_IRQn DMA1_Stream3_IRQn
#define ROSSERIAL_UART_DMA_CLK_EN __HAL_RCC_DMA1_CLK_ENABLE
#define ROSSERUAL_UART_PIN_AF GPIO_AF7_USART3
#define ROSSERIAL_UART_RX_PIN GPIO_PIN_9
#define ROSSERIAL_UART_TX_PIN GPIO_PIN_8
#define ROSERIAL_UART_GPIO_PORT GPIOD
#define ROSSERIAL_GPIO_PORT_CLK_EN __HAL_RCC_GPIOD_CLK_ENABLE

#define HEARTBEAT_LED_PIN GPIO_PIN_14
#define HEARTBEAT_LED_PORT GPIOB
#define HEARTBEAT_LED_PORT_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define STATUS_LED_PIN GPIO_PIN_0
#define STATUS_LED_PORT GPIOB
#define STATUS_LED_PORT_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE

#endif
#ifdef BLACKPILL

#define SWD_PORT_CLK_EN __HAL_RCC_GPIOA_CLK_ENABLE
#define BOARD 2
// TODO recheck all these definitions
#define ROSSERIAL_UART USART1
#define ROSSERIAL_UART_CLK_EN __HAL_RCC_USART1_CLK_ENABLE
#define ROSSERIAL_UART_IRQn USART1_IRQn
#define ROSSERIAL_UART_RXDMA_STREAM DMA1_Stream1
#define ROSSERIAL_UART_TXDMA_STREAM DMA2_Stream3
#define ROSSERIAL_UART_RXDMA_CHANNEL DMA_CHANNEL_4
#define ROSSERIAL_UART_TXDMA_CHANNEL DMA_CHANNEL_4
#define ROSSERIAL_UART_RXDMA_IRQn DMA1_Stream1_IRQn
#define ROSSERIAL_UART_TXDMA_IRQn DMA1_Stream1_IRQn
#define ROSSERIAL_UART_DMA_CLK_EN __HAL_RCC_DMA1_CLK_ENABLE
#define ROSSERUAL_UART_PIN_AF GPIO_AF7_USART1
#define ROSSERIAL_UART_RX_PIN GPIO_PIN_9
#define ROSSERIAL_UART_TX_PIN GPIO_PIN_8
#define ROSERIAL_UART_GPIO_PORT GPIOB
#define ROSSERIAL_GPIO_PORT_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE

#define HEARTBEAT_LED_PIN GPIO_PIN_14
#define HEARTBEAT_LED_PORT GPIOB
#define HEARTBEAT_LED_PORT_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#define STATUS_LED_PIN GPIO_PIN_0
#define STATUS_LED_PORT GPIOB
#define STATUS_LED_PORT_CLK_EN __HAL_RCC_GPIOB_CLK_ENABLE
#endif